FROM mysql:latest

# contraseña root base de datos
ENV MYSQL_ROOT_PASSWORD=root

#nombre base de datos
ENV MYSQL_DATABASE=concesionario

# usuario y contraseña base de datos
ENV MYSQL_USER=root
ENV MYSQL_PASWORD=root

COPY concesionario.sql /docker-entrypoint-initdb.d/
